version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - apt-get install -y unzip
      - apt-get update
      - apt-get install openjdk-17-jdk -y

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html 
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - 1.png
    - aws.gif
    - back.jpg
